[package]
name = "guest-assessor"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[build-dependencies]
hex = { workspace = true }
risc0-build = { workspace = true, features = ["unstable"] }
risc0-build-ethereum = { workspace = true }

[package.metadata.risc0]
methods = ["assessor-guest"]

[package.metadata.release]
release = false
