apiVersion: 1

datasources:
  - name: postgres-taskdb
    type: postgres
    url: $POSTGRES_HOST:$POSTGRES_PORT
    user: $POSTGRES_USER
    access: proxy
    basicAuth: false
    isDefault: true
    secureJsonData:
      password: '$POSTGRES_PASS'
    jsonData:
      sslmode: disable
      database: $POSTGRES_DB
      maxIdleConnsAuto: true
      maxIdleConns: 5
      maxOpenConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    version: 1
    editable: true