[package]
name = "indexer-monitor"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[dependencies]
alloy = { workspace = true, default-features = false }
anyhow = { workspace = true }
aws-config = { version = "1.6", features = ["behavior-version-latest"] }
aws-sdk-cloudwatch = "1.73"
aws-smithy-types = "1.3"
chrono = "0.4"
lambda_runtime = "0.13.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [ "any", "postgres", "sqlite", "runtime-tokio", "json", "migrate", "macros", "runtime-tokio-rustls"] }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "env-filter",
] }

