secretsprovider: awskms:///arn:aws:kms:us-west-2:968153779208:alias/pulumi-secrets-key
encryptedkey: AQICAHhnm/1/W7/xeF2uxmXOGjFzOf6jjMX+KgbMb0K+LSCbsAGhTGWfygcd809D1S2Fd+rMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVv5DUpngmsfLMmx7AgEQgDviJhApZO0WXeLkLgH/qVH+jz3Ya+EgfbkdzV0geaV+p1P6xc4j+4SGQl/lgb0vOIhDMT/vnrLH0pAmaA==
config:
  aws:region: us-west-2
  order-generator-base:PINATA_JWT:
    secure: v1:VGD4b3duR8qDgPcf:hg7a9hzbcbo/Sqj79fp06XpgLsioFNM0gkumdtHBXWQNblz/srhGHjFDaCxkv+GO3jirWewM/woviNaPr4xJlhNPIjkHrhUB0OrVgshGAUwls7T+5uKSbTXhyT5UacEwa+nJvCdn5vwWwlUIT55xjADfRvlzeQYDaqA7UV0t7D4LX9Bn6kY/nM7cfhxodLEEuQGWhve5vlNZ6TQwtcPv/jGh3rC9610Z8DoThYXuRQbbI80MokDBW+7JWy3hZbaTvOMNE7aUaFKU8OVjXzPsYxo4K2v8CkS+2f/DwOBeLy/qtELKd0T8fVbjFSx38i4xDW3RKTic+R49llwb3awK4FCW1bfNxmq9rr6eXEQk3AisVyVpLnlpz2ssCez+fsJDNV7FBrGpT1RmUCxzHsJyGFa/OWVXYVHEBBa21OJnq5IjhAbWHdJZQTsAeqNNGXtfsFpCoUp6bCpyhlYwP0qoup35d1OetvRlmpXjgVUKerDaQ0+T7khtlBB4oIbtdc5BdYb6FL/CcaFZvtGcE9IX6CGAtSuVqbgICgqsHd5E8YvT856UjZ1vFQQ7KO0XlPnNcwpHgx6DbM1vKPZ7ogywcDFx51wnJKhczYPfV5CecmjGWelYH+UjOxsZFVUhB2+FOPwSDc8uTlFqTlhFc/hJX1yLfvo6SzNBVVtRnI33XYBvkJEBESs3Nu/EwuodK8YYAuIQMomsNP7rSTYfiRbKjrFdsZJIuLPZW94u5EcLyLnRNlWZHmDzgLLiMXzcZUBfhQ5Do7s43ab6Nt1tYTpSOpojV6RVzJlTDorm6fd2WhZ8nDJL1h2fdxG8LmnTZu4HeIsa65FFXVIbQos9Lulk8S1oEBYqOYiPRawJMP9mRGW/vwphWkCZ4X/HZoDI+UOZINhczxd1i2ohTd9/t3KUL163ZHQE79qg
  order-generator-base:ETH_RPC_URL:
    secure: v1:AHJX5RgcdGe/gPBl:QyR18cMUudBxUFu/p3oZoSUfxnfl7cYPEWG6+bNpnr3eXbYHAYv9xDAGJObSpzmNv+XfJZScwa7eDQvq6XpPqspg+s7HIfEYan5u34kXQq9F1qjf8A==
  order-generator-base:SLACK_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-alerts-topic
  order-generator-base:PAGERDUTY_ALERTS_TOPIC_ARN: arn:aws:sns:us-west-2:968153779208:boundless-pagerduty-topic
  order-generator-base:BASE_STACK: organization/bootstrap/services-prod
  order-generator-base:BOUNDLESS_MARKET_ADDR: 0x13337C76fE2d1750246B68781ecEe164643b98Ec
  order-generator-base:SET_VERIFIER_ADDR: 0x7aAB646f23D1392d4522CFaB0b7FB5eaf6821d64
  order-generator-base:DOCKER_DIR: ../../
  order-generator-base:DOCKER_TAG: latest
  order-generator-base:LOG_LEVEL: info
  order-generator-base:IPFS_GATEWAY_URL: https://dweb.link
  order-generator-base:CHAIN_ID: "11155111"
  order-generator-base:INTERVAL: "300"
  order-generator-base:LOCK_STAKE_RAW: "500000" # $0.50 USDC
  order-generator-base:MAX_PRICE_PER_MCYCLE: "0.00001"
  order-generator-base:MIN_PRICE_PER_MCYCLE: "0"
  order-generator-base:ORDER_STREAM_URL: https://eth-sepolia.beboundless.xyz
  order-generator-base:GH_TOKEN_SECRET:
    secure: v1:i+l18LS63TZDaTEk:DwR3R7w8tTJCqDQMZpOPF7Ih1xm+xszYALdKhiM+xvSJcPzPhY15QAtamb6RaHjj0g/eOWkHeueQmJY0lmTUNJ9TEte8N4YLfWomNAXJxKKCiXZc7P+S7yy1Gw+f+ljyOXEFDIpQGTO19ZVJ0g==
  order-generator-base:TX_TIMEOUT: "120"
  # Offchain order generator is configured to send small orders that must be locked/fulfilled within 30 mins
  # We use these orders as canaries to monitor the health of the system
  order-generator-offchain:INPUT_MAX_MCYCLES: "10"
  order-generator-offchain:RAMP_UP: "300"
  order-generator-offchain:LOCK_TIMEOUT: "900"
  order-generator-offchain:TIMEOUT: "1500"
  order-generator-offchain:SECONDS_PER_MCYCLE: "0"
  order-generator-offchain:PRIVATE_KEY:
    secure: v1:9iJ6gE5+gp4aipMW:lZlt7k89kafxnLvr8Qe0sStef/3gNEOcr67breAfH/sSrlgL4m6k081WHMUpaU2doI683Sd0TQ+kSnbLKINXfxvqiw/EFfhz4SxOks6d9UI=
  order-generator-offchain:AUTO_DEPOSIT: "15"
  order-generator-offchain:WARN_BALANCE_BELOW: "50"
  order-generator-offchain:ERROR_BALANCE_BELOW: "25"
  order-generator-onchain:WARN_BALANCE_BELOW: "50"
  order-generator-onchain:ERROR_BALANCE_BELOW: "25"
  order-generator-onchain:PRIVATE_KEY:
    secure: v1:X0x504eGSlReaNWU:HHKOYSpWFvByYG23SRcGA2/uvj0i5S09Jfof+tNB/S1ooLrm8vmZ+QXhS3+8loVt8dIKS3H9U4svS5CrV5FHZNQXlAa74cQ3McoDQsIIQ84=
  # Onchain order generator is configured to send larger orders that must be locked/fulfilled within 1 hour
  # Mostly used to send load to the market, but also monitored as a canary.
  order-generator-onchain:RAMP_UP: "600"
  order-generator-onchain:LOCK_TIMEOUT: "900"
  order-generator-onchain:TIMEOUT: "1800"
  order-generator-onchain:SECONDS_PER_MCYCLE: "15"